num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
print()
print("The sum of", num1, "and", num2, "is", num1 + num2)
print("The difference of", num1, "and", num2, "is", num1 - num2)
print("The product of", num1, "and", num2, "is", num1 * num2)
print("The division of", num1, "and", num2, "is", num1 / num2)
print("The modulus of", num1, "and", num2, "is", num1 % num2)
print("The floor division of", num1, "and", num2, "is", num1 // num2)
print("The exponent of", num1, "and", num2, "is", num1 ** num2)